version: LivingWorlds 0.1.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  verbosity: minimal
before_package:
- ps: Copy-Item C:\projects\3DEngine18\Source\$env:CONFIGURATION\3DGameEngine.exe C:\projects\3DEngine18\Game\.
artifacts:
- path: Game
  name: LivingWorlds
deploy:
- provider: GitHub
  description: LivingWorlds
  auth_token:
    secure: piE1WY+KQYZkBVZ0eaCkCJJru7Wzo0OObLas5xrwYWRROcQivrqnrCrK++IW59H9
  draft: true