version: 1.1.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  verbosity: minimal
before_package:
- ps: Copy-Item C:\projects\3DEngine18\Source\$env:CONFIGURATION\3DGameEngine.exe C:\projects\3DEngine18\Game\.
artifacts:
- path: Game
  name: GameAssets
  type: WebDeployPackage
deploy:
- provider: GitHub
  description: AutoRelease
  auth_token:
    secure: zNzTNXUxlkX4kRRIEWI8Mr8ylvoRHYC8RH/tz/xEEJnAQiowo57Izml0qdLCFWND
  draft: true