version: 1.0.{build}
configuration:
- Debug
- Release
build:
  verbosity: minimal
before_package:
- ps: Copy-Item C:\projects\3DEngine18\Source\$env:CONFIGURATION\3DGameEngine.exe C:\projects\3DEngine18\Game\.
artifacts:
- path: Game
  name: GameAssets
  type: WebDeployPackage
deploy:
- provider: GitHub
  description: AutoRelease
  auth_token:
    secure: SCslfI2j/1N3gCQm0QLMH5+1bphYhHgSWx3IB9lAi05Mdsz9J6RHRRuWhAQeFrHDT64cv2NusTbPzySIval8r0ar67oRapaS9NjO/1P0Mqk=
  draft: true
 