version: LivingWorlds-{branch} 0.1.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration:
- Debug
- Release
environment:
  platform: x86
build:
  project: Living Worlds.sln
  verbosity: minimal
before_package:
- ps: >-
    Copy-Item C:\projects\3dmotor18\$env:CONFIGURATION\Living Worlds.exe C:\projects\3dmotor18\Game\.
    Copy-Item C:\projects\3dmotor18\README.md C:\projects\3dmotor18\Game\
artifacts:
- path: Game
  name: Living Worlds
deploy:
- provider: GitHub
  auth_token:
    secure: GeYx4HYpDpN6dKUH00nJz0Yzbe9g98uB74ulCIMOCcsPighlNM5m/E5mGnCuLo+r
  artifact: Living Worlds
  force_update: true
  on:
    branch: master
    CONFIGURATION: Release